name: subway_ody
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# 버전관리 ( Version name, Version Code )
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.6
  riverpod: ^2.3.2
  flutter_svg: ^2.0.5
  hooks_riverpod: ^2.3.2
  json_annotation: ^4.8.1
  flutter_launcher_icons: ^0.13.1
  location: ^4.4.0
  get_it: ^7.6.0
  http: ^0.13.6
  shared_preferences: ^2.1.1
  flutter_exit_app: ^1.1.2
  app_settings: ^4.2.0
  package_info_plus: ^4.0.2
  restart_app: ^1.1.2
  change_app_package_name: ^1.1.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.17
  json_serializable: ^6.6.2
  build_runner: ^2.3.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/fonts/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900

flutter_native_splash:
  image: assets/imgs/splash_bg.png
  image_dark: assets/imgs/splash_bg.png
  color: "#FC4F00"
  color_dark: "#FC4F00"

  # Android 12 이상 버전에서 적용
  android_12:
    image: assets/imgs/splash_bg.png
    image_dark: assets/imgs/splash_bg.png
    color: "#FC4F00"
    color_dark: "#FC4F00"